export const schemeLinkConfig = {
  rootScreen: {
    webview: undefined,
    onBoardingNavigation: undefined,
    splash: undefined,
    mainNavigation: {
      profile: undefined,
      moreReview: undefined,
      offerSentUser: undefined,
      applyStatus: '/my/offer/team/received',
      profilePreview: undefined,
      teamHistory: undefined,
      teamReview: '/my/team-history/review',
      bookmark: undefined,
      offerFromTeam: '/my/offer/user/received',
      teamDetail: undefined,
      joinTeam: undefined,
      offerToTeamHistory: undefined,
      groupDetail: undefined,
      positionSelector: undefined,
      groupCreator: undefined,
      alertPage: undefined,
      setting: undefined,
      alarmSetting: undefined,
      userModifier: undefined,
      etc: undefined,
      opensourcePage: undefined,
      teamEditor: undefined,
      webviewPage: undefined,
      teamComplete: undefined,
      completeSuccess: undefined,
      manageTeammate: undefined,
    },
    mainBottomNavigation: {
      home: {
        groupList: '/home',
        teamMate: undefined,
      },
      team: '/team',
      myPage: undefined,
    },
  },
};
